name: dart_doc_markdown_generator
description: A tool for creating Markdown documentation from Dart files in a Dart/Flutter project.
version: 1.0.2
homepage: https://github.com/Toglefritz/dart_docs_markdown
repository: https://github.com/Toglefritz/dart_docs_markdown

environment:
  sdk: ^3.6.1

dependencies:
  # A library for parsing Dart files.
  analyzer: ^7.2.0
  # Provides lint rules for the Dart analyzer.
  very_good_analysis: ^7.0.0
  path: ^1.9.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
